name: 'Build'

on:
  #push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: dotnet publish -c Release -r win-x64 -f net472 --no-self-contained
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          retention-days: 30
          if-no-files-found: error
          path: .\*
